CREATE TABLE [dbo].[RSSCHANNEL] (
    [ID] BIGINT NOT NULL IDENTITY,
	[COPYRIGHT] NVARCHAR(50) NULL, 
    [DESCRIPTION] NVARCHAR(50) NULL, 
	[LANGUAGE] NVARCHAR(10) NULL, 
    [TITLE] NVARCHAR(50) NULL, 
    [URL] NVARCHAR(100) NULL, 
	[AUTOREFRESH] BIT NOT NULL DEFAULT 0, 
    [IS_DELETED] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_RSSCHANNEL_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
    --,CONSTRAINT [FK_RSSCHANNEL_USER] FOREIGN KEY ([USER_ID]) REFERENCES [USER]([ID]) ON DELETE CASCADE
);

GO

CREATE UNIQUE INDEX [IX_RSSCHANNEL_URL] ON [dbo].[RSSCHANNEL] ([URL])
