CREATE TABLE [dbo].[RSSITEM_BY_USER]
(
	[ITEM_ID] BIGINT NOT NULL , 
    [USER_ID] BIGINT NOT NULL, 
    [READ_STATE] SMALLINT NULL DEFAULT 0, 
    CONSTRAINT [PK_RSSITEM_BY_USER] PRIMARY KEY ([ITEM_ID], [USER_ID]),
	CONSTRAINT [FK_RSSITEM_BY_USER_ITM] FOREIGN KEY ([ITEM_ID]) REFERENCES [RSSITEM]([ID]) ON DELETE CASCADE,
	CONSTRAINT [FK_RSSITEM_BY_USER_USR] FOREIGN KEY ([USER_ID]) REFERENCES [USER]([ID]) ON DELETE CASCADE
)
