CREATE PROCEDURE [dbo].[RC_DELETE_RSSCHANNEL]
	@id int = 0
AS
BEGIN
	DELETE FROM [dbo].[RSSCHANNEL] WHERE [dbo].[RSSCHANNEL].[ID]=@id;
	--UPDATE [dbo].[RSSCHANNEL] SET [dbo].[RSSCHANNEL].[IS_DELETED]=1 WHERE [dbo].[RSSCHANNEL].[ID]=@id;
END
