CREATE PROCEDURE [dbo].[RC_SELECT_RSSCHANNELS]
AS
BEGIN
	SELECT 
		 [dbo].[RSSCHANNEL].[COPYRIGHT]
		,[dbo].[RSSCHANNEL].[DESCRIPTION]
		,[dbo].[RSSCHANNEL].[ID]
		,[dbo].[RSSCHANNEL].[LANGUAGE]
		,[dbo].[RSSCHANNEL].[TITLE]
		,[dbo].[RSSCHANNEL].[URL]
		,'' AS 'NAME'
	FROM
		[dbo].[RSSCHANNEL]
	ORDER BY
		[dbo].[RSSCHANNEL].[ID]
END
